///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: unnecessary_this, avoid_function_literals_in_foreach_calls

class ContactModelData {
/*
{
  "id": 1,
  "text": "Qaynar xətt",
  "number": "914"
} 
*/

  int? id;
  String? text;
  String? number;

  ContactModelData({
    this.id,
    this.text,
    this.number,
  });
  ContactModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    text = json['text']?.toString();
    number = json['number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['text'] = text;
    data['number'] = number;
    return data;
  }
}

class ContactModel {
/*
{
  "data": [
    {
      "id": 1,
      "text": "Qaynar xətt",
      "number": "914"
    }
  ],
  "errors": null
} 
*/

  List<ContactModelData?>? data;
  String? errors;

  ContactModel({
    this.data,
    this.errors,
  });
  ContactModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ContactModelData>[];
      v.forEach((v) {
        arr0.add(ContactModelData.fromJson(v));
      });
      this.data = arr0;
    }
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['errors'] = errors;
    return data;
  }
}
