///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: unnecessary_this, avoid_function_literals_in_foreach_calls, unnecessary_null_comparison

class DebtProfitModelDataFileCategories {
/*
{
  "id": 1,
  "name": "Sənədlər",
  "image": "https://appzeytunpharm.az/storage/file.png",
  "status": 1,
  "delete": 0,
  "created_at": "2020-11-23T01:23:36.000000Z",
  "updated_at": "2021-01-10T05:13:19.000000Z"
} 
*/

  int? id;
  String? name;
  String? image;
  int? status;
  int? delete;
  String? createdAt;
  String? updatedAt;

  DebtProfitModelDataFileCategories({
    this.id,
    this.name,
    this.image,
    this.status,
    this.delete,
    this.createdAt,
    this.updatedAt,
  });
  DebtProfitModelDataFileCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    delete = json['delete']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['delete'] = delete;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class DebtProfitModelDataData {
/*
{
  "type": "0",
  "amount": "340.08",
  "currency": "AZN",
  "balance": "339.35",
  "name": "Vergi",
  "date": "2023-05-11"
} 
*/

  String? type;
  String? amount;
  String? currency;
  String? balance;
  String? name;
  String? date;

  DebtProfitModelDataData({
    this.type,
    this.amount,
    this.currency,
    this.balance,
    this.name,
    this.date,
  });
  DebtProfitModelDataData.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
    balance = json['balance']?.toString();
    name = json['name']?.toString();
    date = json['date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['amount'] = amount;
    data['currency'] = currency;
    data['balance'] = balance;
    data['name'] = name;
    data['date'] = date;
    return data;
  }
}

class DebtProfitModelData {
/*
{
  "data": [
    {
      "type": "0",
      "amount": "340.08",
      "currency": "AZN",
      "balance": "339.35",
      "name": "Vergi",
      "date": "2023-05-11"
    }
  ],
  "fileCategories": [
    {
      "id": 1,
      "name": "Sənədlər",
      "image": "https://appzeytunpharm.az/storage/file.png",
      "status": 1,
      "delete": 0,
      "created_at": "2020-11-23T01:23:36.000000Z",
      "updated_at": "2021-01-10T05:13:19.000000Z"
    }
  ]
} 
*/

  List<DebtProfitModelDataData?>? data;
  List<DebtProfitModelDataFileCategories?>? fileCategories;

  DebtProfitModelData({
    this.data,
    this.fileCategories,
  });
  DebtProfitModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <DebtProfitModelDataData>[];
      v.forEach((v) {
        arr0.add(DebtProfitModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    if (json['fileCategories'] != null) {
      final v = json['fileCategories'];
      final arr0 = <DebtProfitModelDataFileCategories>[];
      v.forEach((v) {
        arr0.add(DebtProfitModelDataFileCategories.fromJson(v));
      });
      fileCategories = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (fileCategories != null) {
      final v = fileCategories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['fileCategories'] = arr0;
    }
    return data;
  }
}

class DebtProfitModel {
/*
{
  "data": {
    "data": [
      {
        "type": "0",
        "amount": "340.08",
        "currency": "AZN",
        "balance": "339.35",
        "name": "Vergi",
        "date": "2023-05-11"
      }
    ],
    "fileCategories": [
      {
        "id": 1,
        "name": "Sənədlər",
        "image": "https://appzeytunpharm.az/storage/file.png",
        "status": 1,
        "delete": 0,
        "created_at": "2020-11-23T01:23:36.000000Z",
        "updated_at": "2021-01-10T05:13:19.000000Z"
      }
    ]
  },
  "errors": null
} 
*/

  DebtProfitModelData? data;
  String? errors;

  DebtProfitModel({
    this.data,
    this.errors,
  });
  DebtProfitModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? DebtProfitModelData.fromJson(json['data'])
        : null;
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['errors'] = errors;
    return data;
  }
}
