///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: unnecessary_this, unnecessary_null_comparison, avoid_function_literals_in_foreach_calls

class DebtMoreModelDataData {
/*
{
  "pharmacy_id": 3752,
  "name": "Əsas müqavilə",
  "balance": "4001.57",
  "currency": "AZN",
  "date": "2023-05-11"
} 
*/

  int? pharmacyId;
  String? name;
  String? balance;
  String? currency;
  String? date;

  DebtMoreModelDataData({
    this.pharmacyId,
    this.name,
    this.balance,
    this.currency,
    this.date,
  });
  DebtMoreModelDataData.fromJson(Map<String, dynamic> json) {
    pharmacyId = json['pharmacy_id']?.toInt();
    name = json['name']?.toString();
    balance = json['balance']?.toString();
    currency = json['currency']?.toString();
    date = json['date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pharmacy_id'] = pharmacyId;
    data['name'] = name;
    data['balance'] = balance;
    data['currency'] = currency;
    data['date'] = date;
    return data;
  }
}

class DebtMoreModelData {
/*
{
  "data": [
    {
      "pharmacy_id": 3752,
      "name": "Əsas müqavilə",
      "balance": "4001.57",
      "currency": "AZN",
      "date": "2023-05-11"
    }
  ]
} 
*/

  List<DebtMoreModelDataData?>? data;

  DebtMoreModelData({
    this.data,
  });
  DebtMoreModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <DebtMoreModelDataData>[];
      v.forEach((v) {
        arr0.add(DebtMoreModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}

class DebtMoreModel {
/*
{
  "data": {
    "data": [
      {
        "pharmacy_id": 3752,
        "name": "Əsas müqavilə",
        "balance": "4001.57",
        "currency": "AZN",
        "date": "2023-05-11"
      }
    ]
  },
  "errors": null
} 
*/

  DebtMoreModelData? data;
  String? errors;

  DebtMoreModel({
    this.data,
    this.errors,
  });
  DebtMoreModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? DebtMoreModelData.fromJson(json['data'])
        : null;
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['errors'] = errors;
    return data;
  }
}
