///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: unnecessary_this, avoid_function_literals_in_foreach_calls

class InformationModelDataSenderData {
/*
{
  "name": "Depo"
} 
*/

  String? name;

  InformationModelDataSenderData({
    this.name,
  });
  InformationModelDataSenderData.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    return data;
  }
}

class InformationModelData {
  int? id;
  int? sender;
  String? title;
  int? categoriesId;
  String? body;
  int? isRead;
  String? date;
  InformationModelDataSenderData? senderData;
  List<File>? files;

  InformationModelData({
    this.id,
    this.sender,
    this.title,
    this.categoriesId,
    this.body,
    this.isRead,
    this.date,
    this.senderData,
    this.files,
  });
  InformationModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    sender = json['sender']?.toInt();
    title = json['title']?.toString();
    categoriesId = json['categories_id']?.toInt();
    body = json['body']?.toString();
    isRead = json['is_read']?.toInt();
    date = json['date']?.toString();
    senderData = (json['sender_data'] != null)
        ? InformationModelDataSenderData.fromJson(json['sender_data'])
        : null;
    files = <File>[];
    if (json['files'] != null) {
      json['files'].forEach((v) {
        files!.add(new File.fromJson(v));
      });
    }

  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['sender'] = sender;
    data['title'] = title;
    data['categories_id'] = categoriesId;
    data['body'] = body;
    data['is_read'] = isRead;
    data['date'] = date;
    if (senderData != null) {
      data['sender_data'] = senderData!.toJson();
    }
    if (this.files != null) {
      data['files'] = this.files!.map((v) => v.toJson()).toList();
    }
    return data;
  }

  @override
  String toString() {
    return 'InformationModelData{id: $id, sender: $sender, title: $title, categoriesId: $categoriesId, body: $body, isRead: $isRead, date: $date, senderData: $senderData, files: $files}';
  }
}
class File {
  int? id;
  String? name;
  String? extension;
  String? link;
  int? type;
  dynamic categoryId;
  int? modelId;
  int? status;
  int? delete;
  dynamic createdAt;
  dynamic updatedAt;

  File(
      {this.id,
        this.name,
        this.extension,
        this.link,
        this.type,
        this.categoryId,
        this.modelId,
        this.status,
        this.delete,
        this.createdAt,
        this.updatedAt});

  File.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    extension = json['extension'];
    link = json['link'];
    type = json['type'];
    categoryId = json['category_id'];
    modelId = json['model_id'];
    status = json['status'];
    delete = json['delete'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['extension'] = this.extension;
    data['link'] = this.link;
    data['type'] = this.type;
    data['category_id'] = this.categoryId;
    data['model_id'] = this.modelId;
    data['status'] = this.status;
    data['delete'] = this.delete;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }

  @override
  String toString() {
    return 'File{id: $id, name: $name, extension: $extension, link: $link, type: $type, categoryId: $categoryId, modelId: $modelId, status: $status, delete: $delete, createdAt: $createdAt, updatedAt: $updatedAt}';
  }
}

class InformationModel {
  List<InformationModelData?>? data;

  InformationModel({
    this.data,
  });
  InformationModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <InformationModelData>[];
      v.forEach((v) {
        arr0.add(InformationModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
