///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: unnecessary_this, avoid_function_literals_in_foreach_calls

class NotificationModelDataRecipientDataRegion {
/*
{
  "id": 37,
  "name": "Suraxanı",
  "address": "Suraxanı r,Əmircan qəs,Çaparidze küç,47",
  "status": 1,
  "delete": 0,
  "created_at": null,
  "updated_at": null
} 
*/

  int? id;
  String? name;
  String? address;
  int? status;
  int? delete;
  String? createdAt;
  String? updatedAt;

  NotificationModelDataRecipientDataRegion({
    this.id,
    this.name,
    this.address,
    this.status,
    this.delete,
    this.createdAt,
    this.updatedAt,
  });
  NotificationModelDataRecipientDataRegion.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    address = json['address']?.toString();
    status = json['status']?.toInt();
    delete = json['delete']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['address'] = address;
    data['status'] = status;
    data['delete'] = delete;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class NotificationModelDataRecipientData {
/*
{
  "id": 3752,
  "fcm_token": null,
  "type": 1,
  "region_id": 37,
  "email": "suraxani565@zeytunpharma.az",
  "password": "$2y$10$BgeNgtGeOz4v1dBAQnnRnOolHSvy0rSQalzBPrTkrI3WFE8Tynl/S",
  "name": "565 Suraxanı",
  "code": "ea0b8301-f1e4-11ec-974a-00505683704f",
  "voen": "1701688171",
  "address": "Bakı ş,Suraxanı r,Zığ şossesi,1A",
  "total_debt_pharmacy": "6163.48",
  "balance": "4288.90",
  "total_debt_warehouse": "2400.00",
  "currency": "AZN",
  "status": 1,
  "is_login": 1,
  "created_at": null,
  "updated_at": null,
  "delete": 0,
  "last_login_date": "2023-05-10 13:18:51",
  "region": {
    "id": 37,
    "name": "Suraxanı",
    "address": "Suraxanı r,Əmircan qəs,Çaparidze küç,47",
    "status": 1,
    "delete": 0,
    "created_at": null,
    "updated_at": null
  }
} 
*/

  int? id;
  String? fcmToken;
  int? type;
  int? regionId;
  String? email;
  String? password;
  String? name;
  String? code;
  String? voen;
  String? address;
  String? totalDebtPharmacy;
  String? balance;
  String? totalDebtWarehouse;
  String? currency;
  int? status;
  int? isLogin;
  String? createdAt;
  String? updatedAt;
  int? delete;
  String? lastLoginDate;
  NotificationModelDataRecipientDataRegion? region;

  NotificationModelDataRecipientData({
    this.id,
    this.fcmToken,
    this.type,
    this.regionId,
    this.email,
    this.password,
    this.name,
    this.code,
    this.voen,
    this.address,
    this.totalDebtPharmacy,
    this.balance,
    this.totalDebtWarehouse,
    this.currency,
    this.status,
    this.isLogin,
    this.createdAt,
    this.updatedAt,
    this.delete,
    this.lastLoginDate,
    this.region,
  });
  NotificationModelDataRecipientData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    fcmToken = json['fcm_token']?.toString();
    type = json['type']?.toInt();
    regionId = json['region_id']?.toInt();
    email = json['email']?.toString();
    password = json['password']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
    voen = json['voen']?.toString();
    address = json['address']?.toString();
    totalDebtPharmacy = json['total_debt_pharmacy']?.toString();
    balance = json['balance']?.toString();
    totalDebtWarehouse = json['total_debt_warehouse']?.toString();
    currency = json['currency']?.toString();
    status = json['status']?.toInt();
    isLogin = json['is_login']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    delete = json['delete']?.toInt();
    lastLoginDate = json['last_login_date']?.toString();
    region = (json['region'] != null)
        ? NotificationModelDataRecipientDataRegion.fromJson(json['region'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['fcm_token'] = fcmToken;
    data['type'] = type;
    data['region_id'] = regionId;
    data['email'] = email;
    data['password'] = password;
    data['name'] = name;
    data['code'] = code;
    data['voen'] = voen;
    data['address'] = address;
    data['total_debt_pharmacy'] = totalDebtPharmacy;
    data['balance'] = balance;
    data['total_debt_warehouse'] = totalDebtWarehouse;
    data['currency'] = currency;
    data['status'] = status;
    data['is_login'] = isLogin;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['delete'] = delete;
    data['last_login_date'] = lastLoginDate;
    if (region != null) {
      data['region'] = region!.toJson();
    }
    return data;
  }
}

class NotificationModelDataSenderDataRegion {
/*
{
  "name": "Region adı",
  "address": "Region ünvanı"
} 
*/

  String? name;
  String? address;

  NotificationModelDataSenderDataRegion({
    this.name,
    this.address,
  });
  NotificationModelDataSenderDataRegion.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    address = json['address']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['address'] = address;
    return data;
  }
}

class NotificationModelDataSenderData {
/*
{
  "id": 2,
  "fcm_token": null,
  "type": 0,
  "region_id": 1,
  "email": "depo@gmail.com",
  "password": "$2y$10$FdQI5V27eonSP.X7PbeN8OOsvN6EN9ikezXNJGD4bsMsGEmIhPqDS",
  "name": "Depo",
  "code": "null",
  "voen": "2349130870264085",
  "address": "Azadliq",
  "total_debt_pharmacy": "7083.31",
  "balance": "2150.36",
  "total_debt_warehouse": "4890.00",
  "currency": "AZN",
  "status": 1,
  "is_login": 1,
  "created_at": null,
  "updated_at": null,
  "delete": 0,
  "last_login_date": "2023-05-10 13:11:01",
  "region": {
    "name": "Region adı",
    "address": "Region ünvanı"
  }
} 
*/

  int? id;
  String? fcmToken;
  int? type;
  int? regionId;
  String? email;
  String? password;
  String? name;
  String? code;
  String? voen;
  String? address;
  String? totalDebtPharmacy;
  String? balance;
  String? totalDebtWarehouse;
  String? currency;
  int? status;
  int? isLogin;
  String? createdAt;
  String? updatedAt;
  int? delete;
  String? lastLoginDate;
  NotificationModelDataSenderDataRegion? region;

  NotificationModelDataSenderData({
    this.id,
    this.fcmToken,
    this.type,
    this.regionId,
    this.email,
    this.password,
    this.name,
    this.code,
    this.voen,
    this.address,
    this.totalDebtPharmacy,
    this.balance,
    this.totalDebtWarehouse,
    this.currency,
    this.status,
    this.isLogin,
    this.createdAt,
    this.updatedAt,
    this.delete,
    this.lastLoginDate,
    this.region,
  });
  NotificationModelDataSenderData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    fcmToken = json['fcm_token']?.toString();
    type = json['type']?.toInt();
    regionId = json['region_id']?.toInt();
    email = json['email']?.toString();
    password = json['password']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
    voen = json['voen']?.toString();
    address = json['address']?.toString();
    totalDebtPharmacy = json['total_debt_pharmacy']?.toString();
    balance = json['balance']?.toString();
    totalDebtWarehouse = json['total_debt_warehouse']?.toString();
    currency = json['currency']?.toString();
    status = json['status']?.toInt();
    isLogin = json['is_login']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    delete = json['delete']?.toInt();
    lastLoginDate = json['last_login_date']?.toString();
    region = (json['region'] != null)
        ? NotificationModelDataSenderDataRegion.fromJson(json['region'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['fcm_token'] = fcmToken;
    data['type'] = type;
    data['region_id'] = regionId;
    data['email'] = email;
    data['password'] = password;
    data['name'] = name;
    data['code'] = code;
    data['voen'] = voen;
    data['address'] = address;
    data['total_debt_pharmacy'] = totalDebtPharmacy;
    data['balance'] = balance;
    data['total_debt_warehouse'] = totalDebtWarehouse;
    data['currency'] = currency;
    data['status'] = status;
    data['is_login'] = isLogin;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['delete'] = delete;
    data['last_login_date'] = lastLoginDate;
    if (region != null) {
      data['region'] = region!.toJson();
    }
    return data;
  }
}

class NotificationModelData {
  int? id;
  int? sender;
  int? recipient;
  int? type;
  String? title;
  int? categoriesId;
  String? body;
  int? isRead;
  String? date;
  int? status;
  int? delete;
  String? createdAt;
  String? updatedAt;
  int? newsId;
  NotificationModelDataSenderData? senderData;
  NotificationModelDataRecipientData? recipientData;

  NotificationModelData({
    this.id,
    this.sender,
    this.recipient,
    this.type,
    this.title,
    this.categoriesId,
    this.body,
    this.isRead,
    this.date,
    this.status,
    this.delete,
    this.createdAt,
    this.updatedAt,
    this.newsId,
    this.senderData,
    this.recipientData,
  });
  NotificationModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    sender = json['sender']?.toInt();
    recipient = json['recipient']?.toInt();
    type = json['type']?.toInt();
    title = json['title']?.toString();
    categoriesId = json['categories_id']?.toInt();
    body = json['body']?.toString();
    isRead = json['is_read']?.toInt();
    date = json['date']?.toString();
    status = json['status']?.toInt();
    delete = json['delete']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    newsId = json['news_id']?.toInt();
    senderData = (json['sender_data'] != null)
        ? NotificationModelDataSenderData.fromJson(json['sender_data'])
        : null;
    recipientData = (json['recipient_data'] != null)
        ? NotificationModelDataRecipientData.fromJson(json['recipient_data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['sender'] = sender;
    data['recipient'] = recipient;
    data['type'] = type;
    data['title'] = title;
    data['categories_id'] = categoriesId;
    data['body'] = body;
    data['is_read'] = isRead;
    data['date'] = date;
    data['status'] = status;
    data['delete'] = delete;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['news_id'] = newsId;
    if (senderData != null) {
      data['sender_data'] = senderData!.toJson();
    }
    if (recipientData != null) {
      data['recipient_data'] = recipientData!.toJson();
    }
    return data;
  }

  @override
  String toString() {
    return 'NotificationModelData{id: $id, sender: $sender, recipient: $recipient, type: $type, title: $title, categoriesId: $categoriesId, body: $body, isRead: $isRead, date: $date, status: $status, delete: $delete, createdAt: $createdAt, updatedAt: $updatedAt, newsId: $newsId, senderData: $senderData, recipientData: $recipientData}';
  }
}

class NotificationModel {
  List<NotificationModelData?>? data;
  String? errors;

  NotificationModel({
    this.data,
    this.errors,
  });
  NotificationModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <NotificationModelData>[];
      v.forEach((v) {
        arr0.add(NotificationModelData.fromJson(v));
      });
      this.data = arr0;
    }
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['errors'] = errors;
    return data;
  }

  @override
  String toString() {
    return 'NotificationModel{data: $data, errors: $errors}';
  }
}
