///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: unnecessary_null_comparison, unnecessary_this, avoid_function_literals_in_foreach_calls

class PaymentsModelDataData {
/*
{
  "pharmacy_id": 3752,
  "type": "0",
  "amount": "500",
  "currency": "AZN",
  "balance": "3501.71",
  "name": "Əsas müqavilə",
  "operation": "Nəğd pul ödənişi",
  "date": "2023-04-12"
} 
*/

  int? pharmacyId;
  String? type;
  String? amount;
  String? currency;
  String? balance;
  String? name;
  String? operation;
  String? date;

  PaymentsModelDataData({
    this.pharmacyId,
    this.type,
    this.amount,
    this.currency,
    this.balance,
    this.name,
    this.operation,
    this.date,
  });
  PaymentsModelDataData.fromJson(Map<String, dynamic> json) {
    pharmacyId = json['pharmacy_id']?.toInt();
    type = json['type']?.toString();
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
    balance = json['balance']?.toString();
    name = json['name']?.toString();
    operation = json['operation']?.toString();
    date = json['date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pharmacy_id'] = pharmacyId;
    data['type'] = type;
    data['amount'] = amount;
    data['currency'] = currency;
    data['balance'] = balance;
    data['name'] = name;
    data['operation'] = operation;
    data['date'] = date;
    return data;
  }
}

class PaymentsModelData {
/*
{
  "data": [
    {
      "pharmacy_id": 3752,
      "type": "0",
      "amount": "500",
      "currency": "AZN",
      "balance": "3501.71",
      "name": "Əsas müqavilə",
      "operation": "Nəğd pul ödənişi",
      "date": "2023-04-12"
    }
  ]
} 
*/

  List<PaymentsModelDataData?>? data;

  PaymentsModelData({
    this.data,
  });
  PaymentsModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PaymentsModelDataData>[];
      v.forEach((v) {
        arr0.add(PaymentsModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}

class PaymentsModel {
/*
{
  "data": {
    "data": [
      {
        "pharmacy_id": 3752,
        "type": "0",
        "amount": "500",
        "currency": "AZN",
        "balance": "3501.71",
        "name": "Əsas müqavilə",
        "operation": "Nəğd pul ödənişi",
        "date": "2023-04-12"
      }
    ]
  },
  "errors": null
} 
*/

  PaymentsModelData? data;
  String? errors;

  PaymentsModel({
    this.data,
    this.errors,
  });
  PaymentsModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? PaymentsModelData.fromJson(json['data'])
        : null;
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['errors'] = errors;
    return data;
  }
}
