// ignore_for_file: body_might_complete_normally_nullable, avoid_print, unnecessary_this, avoid_function_literals_in_foreach_calls
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PharmacyListModelDataRegion {
/*
{
  "id": 57,
  "name": "Ağsu",
  "address": "M.Rəsulzadə 123",
  "status": 1,
  "delete": 0,
  "created_at": null,
  "updated_at": null
} 
*/

  int? id;
  String? name;
  String? address;
  int? status;
  int? delete;
  String? createdAt;
  String? updatedAt;

  PharmacyListModelDataRegion({
    this.id,
    this.name,
    this.address,
    this.status,
    this.delete,
    this.createdAt,
    this.updatedAt,
  });
  PharmacyListModelDataRegion.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    address = json['address']?.toString();
    status = json['status']?.toInt();
    delete = json['delete']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['address'] = address;
    data['status'] = status;
    data['delete'] = delete;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class PharmacyListModelData {
/*
{
  "id": 900,
  "fcm_token": "c9RwSs7I6EB-rDgYUdPT9S:APA91bEP9-HZlzAJn_0xt74QHb0YiYMMAjfZ_FMCj9AJ60MSfPeKlyGLm-TD18Fn46qnkrdOXYKafVLLG2XCSHd9j7IzXOH7aMsUJ-0Ka1_70uJhfHN60QxfZcnmVpQ4yK0kIlg1gu7g",
  "type": 1,
  "region_id": 57,
  "email": "1_Agsu@zeytunpharma.az",
  "password": "$2y$10$K/HnZMNrGFIrXEbBQIWhcu9M4wzkTdkjATfz0i3KzUXP66CowISgi",
  "name": "1 AĞSU VIP class",
  "code": "ccc1c378-47ff-11e6-8043-74d435fc9d37",
  "voen": "1701688171",
  "address": "M,Rəsulzadə küçəsi /Molla Vəli Vidadı küçəsi 3-cü dalan 12",
  "total_debt_pharmacy": "11741.87",
  "balance": "11726.70",
  "total_debt_warehouse": "0.00",
  "currency": "AZN",
  "status": 1,
  "is_login": 1,
  "created_at": null,
  "updated_at": null,
  "delete": 0,
  "last_login_date": "2023-04-25 13:48:15",
  "region": {
    "id": 57,
    "name": "Ağsu",
    "address": "M.Rəsulzadə 123",
    "status": 1,
    "delete": 0,
    "created_at": null,
    "updated_at": null
  }
} 
*/

  int? id;
  String? fcmToken;
  int? type;
  int? regionId;
  String? email;
  String? password;
  String? name;
  String? code;
  String? voen;
  String? address;
  String? totalDebtPharmacy;
  String? balance;
  String? totalDebtWarehouse;
  String? currency;
  int? status;
  int? isLogin;
  String? createdAt;
  String? updatedAt;
  int? delete;
  String? lastLoginDate;
  PharmacyListModelDataRegion? region;

  PharmacyListModelData({
    this.id,
    this.fcmToken,
    this.type,
    this.regionId,
    this.email,
    this.password,
    this.name,
    this.code,
    this.voen,
    this.address,
    this.totalDebtPharmacy,
    this.balance,
    this.totalDebtWarehouse,
    this.currency,
    this.status,
    this.isLogin,
    this.createdAt,
    this.updatedAt,
    this.delete,
    this.lastLoginDate,
    this.region,
  });
  PharmacyListModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    fcmToken = json['fcm_token']?.toString();
    type = json['type']?.toInt();
    regionId = json['region_id']?.toInt();
    email = json['email']?.toString();
    password = json['password']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
    voen = json['voen']?.toString();
    address = json['address']?.toString();
    totalDebtPharmacy = json['total_debt_pharmacy']?.toString();
    balance = json['balance']?.toString();
    totalDebtWarehouse = json['total_debt_warehouse']?.toString();
    currency = json['currency']?.toString();
    status = json['status']?.toInt();
    isLogin = json['is_login']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    delete = json['delete']?.toInt();
    lastLoginDate = json['last_login_date']?.toString();
    region = (json['region'] != null)
        ? PharmacyListModelDataRegion.fromJson(json['region'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['fcm_token'] = fcmToken;
    data['type'] = type;
    data['region_id'] = regionId;
    data['email'] = email;
    data['password'] = password;
    data['name'] = name;
    data['code'] = code;
    data['voen'] = voen;
    data['address'] = address;
    data['total_debt_pharmacy'] = totalDebtPharmacy;
    data['balance'] = balance;
    data['total_debt_warehouse'] = totalDebtWarehouse;
    data['currency'] = currency;
    data['status'] = status;
    data['is_login'] = isLogin;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['delete'] = delete;
    data['last_login_date'] = lastLoginDate;
    if (region != null) {
      data['region'] = region!.toJson();
    }
    return data;
  }
}

class PharmacyListModel {
/*
{
  "data": [
    {
      "id": 900,
      "fcm_token": "c9RwSs7I6EB-rDgYUdPT9S:APA91bEP9-HZlzAJn_0xt74QHb0YiYMMAjfZ_FMCj9AJ60MSfPeKlyGLm-TD18Fn46qnkrdOXYKafVLLG2XCSHd9j7IzXOH7aMsUJ-0Ka1_70uJhfHN60QxfZcnmVpQ4yK0kIlg1gu7g",
      "type": 1,
      "region_id": 57,
      "email": "1_Agsu@zeytunpharma.az",
      "password": "$2y$10$K/HnZMNrGFIrXEbBQIWhcu9M4wzkTdkjATfz0i3KzUXP66CowISgi",
      "name": "1 AĞSU VIP class",
      "code": "ccc1c378-47ff-11e6-8043-74d435fc9d37",
      "voen": "1701688171",
      "address": "M,Rəsulzadə küçəsi /Molla Vəli Vidadı küçəsi 3-cü dalan 12",
      "total_debt_pharmacy": "11741.87",
      "balance": "11726.70",
      "total_debt_warehouse": "0.00",
      "currency": "AZN",
      "status": 1,
      "is_login": 1,
      "created_at": null,
      "updated_at": null,
      "delete": 0,
      "last_login_date": "2023-04-25 13:48:15",
      "region": {
        "id": 57,
        "name": "Ağsu",
        "address": "M.Rəsulzadə 123",
        "status": 1,
        "delete": 0,
        "created_at": null,
        "updated_at": null
      }
    }
  ],
  "errors": null
} 
*/

  List<PharmacyListModelData?>? data;
  String? errors;

  PharmacyListModel({
    this.data,
    this.errors,
  });
  PharmacyListModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PharmacyListModelData>[];
      v.forEach((v) {
        arr0.add(PharmacyListModelData.fromJson(v));
      });
      this.data = arr0;
    }
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['errors'] = errors;
    return data;
  }
}
