///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: unnecessary_null_comparison

class RefreshTokenModelData {
/*
{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBwemV5dHVucGhhcm0uYXpcL2FwaVwvcmVmcmVzaCIsImlhdCI6MTY4MzU0OTQ3OSwiZXhwIjoxNjg2MjkwNTgxLCJuYmYiOjE2ODM2OTg1ODEsImp0aSI6IlN0b2Izb2RDRU5UUXJGbVUiLCJzdWIiOjIsInBydiI6IjUyMmExYTY1ZTEyNjg4M2M0YWIwNTA0NGEwNDM3NTVlOThlMjU1NWMifQ.Wl-xuoJNkz78aahWPsx8sDdWrXfh6IRru1oAm5t8HGQ",
  "token_type": "bearer",
  "expires_in": "54000"
} 
*/

  String? accessToken;
  String? tokenType;
  String? expiresIn;

  RefreshTokenModelData({
    this.accessToken,
    this.tokenType,
    this.expiresIn,
  });
  RefreshTokenModelData.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token']?.toString();
    tokenType = json['token_type']?.toString();
    expiresIn = json['expires_in']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['access_token'] = accessToken;
    data['token_type'] = tokenType;
    data['expires_in'] = expiresIn;
    return data;
  }
}

class RefreshTokenModel {
/*
{
  "data": {
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBwemV5dHVucGhhcm0uYXpcL2FwaVwvcmVmcmVzaCIsImlhdCI6MTY4MzU0OTQ3OSwiZXhwIjoxNjg2MjkwNTgxLCJuYmYiOjE2ODM2OTg1ODEsImp0aSI6IlN0b2Izb2RDRU5UUXJGbVUiLCJzdWIiOjIsInBydiI6IjUyMmExYTY1ZTEyNjg4M2M0YWIwNTA0NGEwNDM3NTVlOThlMjU1NWMifQ.Wl-xuoJNkz78aahWPsx8sDdWrXfh6IRru1oAm5t8HGQ",
    "token_type": "bearer",
    "expires_in": "54000"
  }
} 
*/

  RefreshTokenModelData? data;

  RefreshTokenModel({
    this.data,
  });
  RefreshTokenModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? RefreshTokenModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
