///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: unnecessary_null_comparison

class TotalDebtModelDataData {
/*
{
  "total_debt_pharmacy": "17270.56",
  "total_debt_warehouse": "1325.94",
  "balance": "14859.56"
} 
*/

  String? totalDebtPharmacy;
  String? totalDebtWarehouse;
  String? balance;

  TotalDebtModelDataData({
    this.totalDebtPharmacy,
    this.totalDebtWarehouse,
    this.balance,
  });
  TotalDebtModelDataData.fromJson(Map<String, dynamic> json) {
    totalDebtPharmacy = json['total_debt_pharmacy']?.toString();
    totalDebtWarehouse = json['total_debt_warehouse']?.toString();
    balance = json['balance']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_debt_pharmacy'] = totalDebtPharmacy;
    data['total_debt_warehouse'] = totalDebtWarehouse;
    data['balance'] = balance;
    return data;
  }
}

class TotalDebtModelData {
/*
{
  "data": {
    "total_debt_pharmacy": "17270.56",
    "total_debt_warehouse": "1325.94",
    "balance": "14859.56"
  }
} 
*/

  TotalDebtModelDataData? data;

  TotalDebtModelData({
    this.data,
  });
  TotalDebtModelData.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? TotalDebtModelDataData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class TotalDebtModel {
/*
{
  "data": {
    "data": {
      "total_debt_pharmacy": "17270.56",
      "total_debt_warehouse": "1325.94",
      "balance": "14859.56"
    }
  },
  "errors": null
} 
*/

  TotalDebtModelData? data;
  String? errors;

  TotalDebtModel({
    this.data,
    this.errors,
  });
  TotalDebtModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? TotalDebtModelData.fromJson(json['data'])
        : null;
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['errors'] = errors;
    return data;
  }
}
