///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: unnecessary_this, avoid_function_literals_in_foreach_calls

class UnregisteredModelDataRegion {
/*
{
  "id": 52,
  "name": "Cəlilabad",
  "address": "Qurtuluş küçəsi 186b",
  "status": 1,
  "delete": 0,
  "created_at": null,
  "updated_at": null
} 
*/

  int? id;
  String? name;
  String? address;
  int? status;
  int? delete;
  String? createdAt;
  String? updatedAt;

  UnregisteredModelDataRegion({
    this.id,
    this.name,
    this.address,
    this.status,
    this.delete,
    this.createdAt,
    this.updatedAt,
  });
  UnregisteredModelDataRegion.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    address = json['address']?.toString();
    status = json['status']?.toInt();
    delete = json['delete']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['address'] = address;
    data['status'] = status;
    data['delete'] = delete;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class UnregisteredModelData {
/*
{
  "id": 914,
  "fcm_token": null,
  "type": 1,
  "region_id": 52,
  "email": "16_Celilabad@zeytunpharma.az",
  "password": "$2y$10$TmLCmq/yJMt1jQJoRc5xM.GoIoBWrTaIIx8imKUFXXhv.GiOa8p7m",
  "name": "16 Cəlilabad VIP class",
  "code": "df3ce51b-3806-11e8-80c0-000c29f7b3d6",
  "voen": "1701688171",
  "address": "Alar kəndi",
  "total_debt_pharmacy": "15054.10",
  "balance": "13144.90",
  "total_debt_warehouse": "0.00",
  "currency": "AZN",
  "status": 1,
  "is_login": 0,
  "created_at": null,
  "updated_at": null,
  "delete": 0,
  "last_login_date": null,
  "region": {
    "id": 52,
    "name": "Cəlilabad",
    "address": "Qurtuluş küçəsi 186b",
    "status": 1,
    "delete": 0,
    "created_at": null,
    "updated_at": null
  }
} 
*/

  int? id;
  String? fcmToken;
  int? type;
  int? regionId;
  String? email;
  String? password;
  String? name;
  String? code;
  String? voen;
  String? address;
  String? totalDebtPharmacy;
  String? balance;
  String? totalDebtWarehouse;
  String? currency;
  int? status;
  int? isLogin;
  String? createdAt;
  String? updatedAt;
  int? delete;
  String? lastLoginDate;
  UnregisteredModelDataRegion? region;

  UnregisteredModelData({
    this.id,
    this.fcmToken,
    this.type,
    this.regionId,
    this.email,
    this.password,
    this.name,
    this.code,
    this.voen,
    this.address,
    this.totalDebtPharmacy,
    this.balance,
    this.totalDebtWarehouse,
    this.currency,
    this.status,
    this.isLogin,
    this.createdAt,
    this.updatedAt,
    this.delete,
    this.lastLoginDate,
    this.region,
  });
  UnregisteredModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    fcmToken = json['fcm_token']?.toString();
    type = json['type']?.toInt();
    regionId = json['region_id']?.toInt();
    email = json['email']?.toString();
    password = json['password']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
    voen = json['voen']?.toString();
    address = json['address']?.toString();
    totalDebtPharmacy = json['total_debt_pharmacy']?.toString();
    balance = json['balance']?.toString();
    totalDebtWarehouse = json['total_debt_warehouse']?.toString();
    currency = json['currency']?.toString();
    status = json['status']?.toInt();
    isLogin = json['is_login']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    delete = json['delete']?.toInt();
    lastLoginDate = json['last_login_date']?.toString();
    region = (json['region'] != null)
        ? UnregisteredModelDataRegion.fromJson(json['region'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['fcm_token'] = fcmToken;
    data['type'] = type;
    data['region_id'] = regionId;
    data['email'] = email;
    data['password'] = password;
    data['name'] = name;
    data['code'] = code;
    data['voen'] = voen;
    data['address'] = address;
    data['total_debt_pharmacy'] = totalDebtPharmacy;
    data['balance'] = balance;
    data['total_debt_warehouse'] = totalDebtWarehouse;
    data['currency'] = currency;
    data['status'] = status;
    data['is_login'] = isLogin;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['delete'] = delete;
    data['last_login_date'] = lastLoginDate;
    if (region != null) {
      data['region'] = region!.toJson();
    }
    return data;
  }
}

class UnregisteredModel {
/*
{
  "data": [
    {
      "id": 914,
      "fcm_token": null,
      "type": 1,
      "region_id": 52,
      "email": "16_Celilabad@zeytunpharma.az",
      "password": "$2y$10$TmLCmq/yJMt1jQJoRc5xM.GoIoBWrTaIIx8imKUFXXhv.GiOa8p7m",
      "name": "16 Cəlilabad VIP class",
      "code": "df3ce51b-3806-11e8-80c0-000c29f7b3d6",
      "voen": "1701688171",
      "address": "Alar kəndi",
      "total_debt_pharmacy": "15054.10",
      "balance": "13144.90",
      "total_debt_warehouse": "0.00",
      "currency": "AZN",
      "status": 1,
      "is_login": 0,
      "created_at": null,
      "updated_at": null,
      "delete": 0,
      "last_login_date": null,
      "region": {
        "id": 52,
        "name": "Cəlilabad",
        "address": "Qurtuluş küçəsi 186b",
        "status": 1,
        "delete": 0,
        "created_at": null,
        "updated_at": null
      }
    }
  ],
  "errors": null
} 
*/

  List<UnregisteredModelData?>? data;
  String? errors;

  UnregisteredModel({
    this.data,
    this.errors,
  });
  UnregisteredModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <UnregisteredModelData>[];
      v.forEach((v) {
        arr0.add(UnregisteredModelData.fromJson(v));
      });
      this.data = arr0;
    }
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['errors'] = errors;
    return data;
  }
}
