///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WorkerModelEmployees {
/*
{
  "Name": "Nərimanlı Nərman Tərlan ",
  "JobTitle": "Xəzinədar",
  "Salary": 450
} 
*/

  String? Name;
  String? JobTitle;
  int? Salary;

  WorkerModelEmployees({
    this.Name,
    this.JobTitle,
    this.Salary,
  });
  WorkerModelEmployees.fromJson(Map<String, dynamic> json) {
    Name = json['Name']?.toString();
    JobTitle = json['JobTitle']?.toString();
    Salary = json['Salary']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Name'] = Name;
    data['JobTitle'] = JobTitle;
    data['Salary'] = Salary;
    return data;
  }
}

class WorkerModel {
/*
{
  "message": "success",
  "Employees": [
    {
      "Name": "Nərimanlı Nərman Tərlan ",
      "JobTitle": "Xəzinədar",
      "Salary": 450
    }
  ]
} 
*/

  String? message;
  List<WorkerModelEmployees?>? Employees;

  WorkerModel({
    this.message,
    this.Employees,
  });
  WorkerModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    if (json['Employees'] != null) {
      final v = json['Employees'];
      final arr0 = <WorkerModelEmployees>[];
      v.forEach((v) {
        arr0.add(WorkerModelEmployees.fromJson(v));
      });
      Employees = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    if (Employees != null) {
      final v = Employees;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Employees'] = arr0;
    }
    return data;
  }
}
